name: Experimental Azure CLI pipeline

on:
  push:
    branches:
      - develop
      - cli-deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch resources
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SP_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.33.1
          inlineScript: |
            az account show
            az storage -h

#      - name: Set up .NET Core
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: '6.0.x'
#          include-prerelease: true
#
#      - name: Build with dotnet
#        run: dotnet build --configuration Release
#
#      - name: dotnet publish
#        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp